### ISSUE TITLE
automatic printing

### ISSUE THREAD

**Issue by joshuago78** [gri-is/selfcheck#11]

**Comment by dnoneill** [comment]
As of 2/2, will continue searching.
The only way I found to add automatic printing to a script was with Internet Explorer.  Otherwise these might be the best options.  
**Chrome**
add to the end a chrome shortcut --disable-print-preview
https://mycartpos.zendesk.com/hc/en-us/articles/200868343-Enable-kiosk-printing-print-automatically-for-Google-Chrome-on-Windows
**Firefox**
about:config in url
Right click choose New > Boolean
preference name: print.always_print_silent
click OK.
