### ISSUE TITLE
force logout with a timer

### ISSUE THREAD

**Issue by joshuago78** [gri-is/selfcheck#16]
Let's logout the user after 60 seconds of inactivity

**Comment by dnoneill** [comment]
I have pushed the branch with this functionality, however I am unsure it should be implemented.  Because of the way the original application is set up, with only one html page, using the logout function in the inactive function causes the application to switch between the login page and the checkout page.  The only way I have found around this is to basically refresh the page, and it refreshes every 60 seconds, even on the login screen.
